<h2>Statistic</h2>
<ul>
    <li><a href="/ce/statistic/cedefinition/<?php echo CalibrationExercise::COL_ID . "/" . $this->ceId?>">CE definition</a> </li>
    <li><a href="/ce/statistic/images/<?php echo CalibrationExercise::COL_ID . "/" . $this->ceId?>">list of the images and the connected fish data</a> </li>
    <li><a href="/ce/statistic/annotations/<?php echo CalibrationExercise::COL_ID . "/" . $this->ceId?>">annotations</a> </li>
    <li><a href="/ce/statistic/participants/<?php echo CalibrationExercise::COL_ID . "/" . $this->ceId?>">list of the participants</a> </li>
    <li><a href="/ce/statistic/alldistances/<?php echo CalibrationExercise::COL_ID . "/" . $this->ceId?>">all distances</a> </li>
</ul>