<h2>Statistic (Training)</h2>
<ul>
    <li><a href="/ce/statistic/trainingannotation/<?php echo CalibrationExercise::COL_ID . "/" . $this->ceId?>">annotations</a> </li>
    <li><a href="/ce/statistic/images/<?php echo CalibrationExercise::COL_ID . "/" . $this->ceId?>">list of the images and the connected fish data</a> </li>
    <li><a href="/ce/statistic/cedefinition/<?php echo CalibrationExercise::COL_ID . "/" . $this->ceId?>">CE definition</a> </li>
</ul>