<?php
/**
 * Beschreibung: ???
 * Diese Datei regelt vieles
 *
 * @name       Datei: 
 * @abstract   siehe oben
 * @author     Norman Rauthe (nr) <nr@zadi.de>
 * @copyright  Copyright (c) 2009, BLE, Ref. 422, Norman Rauthe (nr) 
 * @version    Version vom 30.11.2009
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
?>
<h3 style="color:red"><?php echo $this->massage; ?></h3>
<?php echo $this->form; ?>