<?php ?><!--  -->
<h2>Imprint</h2><br />
This web site respectively web application - further called WebGR - is in a test state.<br />
This instance of WebGR is hosted within the development of the EU project<br />
WebGR - Web services for support of Growth and Reproduction Studies.<br />
WebGR is funded by EC/DGMARE.<br />
<br /><br />
Project leadership<br />
Ernesto Jardim - Fisheries Scientist<br />
ernesto[AT]ipimar[DOT]pt<br />
IPIMAR: National Laboratory of Marine Research, Unit of Marine Resources<br />
Av. Brasilia, 1449-006 Lisboa, Portugal<br />