<?php
/**
 * @author     Tanja Nuerge (tn) <tn@zadi.de>
 * @copyright  Copyright (c) 2009, BLE, Ref. 422, Tanja Nuerge (tn) 
 * @version    Version vom 16.11.2009 um 16:21:11 Uhr
 *
*/

?>
<h2>License</h2>
<h3>1. Software</h3>
<div>The software WebGR, as not noted otherwise, is licensed under the
Creative Commons Version 3.0 Attribution-Noncommercial-Share Alike 3.0
Unported. 
<br />The authors are:
<br /><br />
<div>IPIMAR (Tender coordinator) - Laboratório Nacional de
Recursos Biológicos – IPIMAR (Portugal)</div>

<div>AFBI - The Agri-Food &amp; Biosciences Institute (UK)</div>

<div>AZTI - AZTI Foundation (Spain)</div>

<div>BLE - Federal Agency for Agriculture and Food
(Germany)</div>

<div>vTI - Johann Heinrich von Thünen Institute (Germany)</div>

<div>HCMR - Hellenic Centre for Marine Research (Greece)</div>

<div>IEO - Instituto Español de Oceanografia (Spain)</div>

<div>IFREMER - Institut français de recherche pour
l’exploitation de la mer (France)</div>

<div>IMARES - Wageningen IMARES (The Netherlands)</div>

<div>IMR - Institute of Marine Research (Norway)</div>

<div>SBF - Swedish Board of Fisheries (Sweden)</div>

<div>SIBM - Italian Society for Marine Biology (Italy)</div>
</div>

<h3>2. Content</h3>
<div>The uploaded images by users and the user generated content - data
describing individual objects, images, image annotations, resulting data
by individuals' and groups' interpretation - are licensed under the
Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported. Do
not import copyrighted data.</div>


<h3>3. Software library</h3>
<div>The software depends on Zend Framework, which at the time of writing is
licensed under the BSD license.</div>

<h3>4. Security</h3>
<div>The authors encourage the operator of the software to use a intrusion
detection system like PHPIDS, which at the time of writing is licensed
under the LGPL.</div>
<hr />
<div>Creative Commons Version 3.0 Attribution-Noncommercial-Share Alike 3.0
Unported</div>
<div>You are free:
<ul>
<li>to Share — to copy, distribute and transmit the work</li>
<li>to Remix — to adapt the work</li>
</ul>
Under the following conditions:

<ul>
<li>Attribution — You must attribute the work in the manner specified by the
author or licensor (but not in any way that suggests that they endorse
you or your use of the work).<div>Attribute this work:
Information
What does "Attribute this work" mean?
The page you came from contained embedded licensing metadata, including
how the creator wishes to be attributed for re-use. You can use the HTML
here to cite the work. Doing so will also include metadata on your page
so that others can find the original work as well.</div></li>
<li>Noncommercial — You may not use this work for commercial purposes.</li>
<li>Share Alike — If you alter, transform, or build upon this work, you may
distribute the resulting work only under the same or similar license to
this one.<div>With the understanding that:</div>
	<ul>
		<li>Waiver — Any of the above conditions can be waived if you get
		permission from the copyright holder.</li>
		<li>Other Rights — In no way are any of the following rights affected by
        the license:
            <ul>
                <li>Your fair dealing or fair use rights;</li>
                <li>The author's moral rights;</li>
                <li>Rights other persons may have either in the work itself or in how the
                work is used, such as publicity or privacy rights.</li>
            </ul>
        </li>
	</ul>
</li>
<li>Notice — For any reuse or distribution, you must make clear to others
the license terms of this work. The best way to do this is with a link
to this web page.
[Source: http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en]</li>
</ul> 
</div>

<hr />

<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License</a>.