<?php
/**
 * @author     Tanja Nuerge (tn) <tn@zadi.de>
 * @copyright  Copyright (c) 2009, BLE, Ref. 422, Tanja Nuerge (tn) 
 * @version    Version vom 16.11.2009 um 16:06:50 Uhr
 *
*/

?>
<h2>Search</h2>
<div>
<ul>    
    <li><a href="/ce/search/form/">Search calibration exercises</a></li>
    <li><a href="/fish/search/reset/">Search fish</a></li>
    <li><a href="/image/search/reset/">Search image</a></li>
    <li><a href="/user/search/index/">Search user</a></li>
    <li><a href="/workshop/search/list">List all workshops</a></li>
</ul>
</div>