<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
            id="WebGRtest" width="100%" height="600px"
            codebase="http://fpdownload.macromedia.com/get/flashplayer/current/swflash.cab">
            <param name="movie" value="/scripts/upload.swf" />
            <param name="quality" value="high" />
            <param name="bgcolor" value="#808080" />
            <param name="allowScriptAccess" value="sameDomain" />
            <param name="viewstate" value="maxState"/>
            <embed src="/scripts/upload.swf?version=1.1.0" quality="high" bgcolor="#808080"
                width="100%" height="600px" name="WebGRtest" align="middle"
                play="true"
                loop="false"
                quality="high"
                allowScriptAccess="sameDomain"
                type="application/x-shockwave-flash"
                pluginspage="http://www.adobe.com/go/getflashplayer">
            </embed>
    </object>
    
    <!-- form method="post" action="/image/batch/upload/key/1234" enctype="multipart/form-data">
    <input name="Filedata" type="file" size="50" maxlength="100000" accept="text/*">
    <input type="submit" name="upload">
    </form -->