<?php
/**
 * Beschreibung folgt....
 *
 * @name       login.phtml
 * @abstract   s. o.
 * @author     Ralf von der Mark (vdM) <vdM@zadi.de>
 * @copyright  Copyright (c) 2008, BLE, Ref. 421, Ralf von der Mark (vdM)
 * @version    Version vom 05.11.2008 um 12:18:01 Uhr
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
?>
<?php echo $this->warning ?>
Welcome to WebGR.
<br></br>
<br></br>
WebGR is a European project that aims to develop Open Source software
to support studies of fish growth and reproduction. In particular it
promotes the use of online services to organise calibration workshops.
<br></br>
<br></br>
Scientists, who read otoliths to identify the ages of individual fish,
have carried out calibration workshops for many years, to fine-tune
their interpretation of the ages of fish within individual stocks or
species. Calibration workshops have also recently been extended to
cover the identification of fish gonad maturity stages. In general
WebGR can be applied to all situations, where individual scientists
need to discuss the interpretation of a protocol, for the
identification of the status of biological material.
<br></br>
<br></br>
The consortium is constituted by: Laboratório Nacional de Recursos
Biológicos – IPIMAR (Portugal) – Consortium leader, The Agri-Food &
Biosciences Institute (UK), AZTI Tecnalia Foundation (Spain), Federal
Agency for Agriculture and Food (Germany), Johann Heinrich von Thünen
Institute (Germany), Hellenic Centre for Marine Research (Greece),
Instituto Español de Oceanografia (Spain), Institut français de
recherche pour l’exploitation de la mer (France), Institute for Marine
Resources & Ecosystem Studies (The Netherlands), Institute of Marine
Research (Norway), Swedish Board of Fisheries (Sweden), Italian
Society for Marine Biology (Italy).
<br></br>
<br></br>
Note that all information uploaded will be under a Creative Commons
Attribution-Share Alike 3.0 Unported License (link this to <a href="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-Share Alike 3.0 Unported License</a>.
<br></br>
<br></br>
For more information please visit <a href="http://webgr.berlios.de">http://webgr.berlios.de</a>.
<br></br>
<br></br>
Enjoy !
<br></br>
The WebGR team.
<?php echo $this->form;?>