<h2>Manuals</h2>
<ul>
    <li><a href="/infoFiles/WebGRusermanual_V_1_1_0.pdf">User manual</a></li>
    <li><a href="/infoFiles/WebGR installation and setup_V_1_1_0.pdf">Installation manual</a></li>
</ul>

<h2>Available video tutorials</h2>
<ul>
    <li><a href="/scripts/makeAnnotations.swf">Make an annotation</a></li>
    <li><a href="/scripts/makeGroupAnnotation.swf">Make a group discussion</a></li>
    <li><a href="/scripts/batchImageUploadManualAssociation.swf">Batch image upload</a></li>
</ul>
Minimal resolution 1024x768, better 1200x800+<br>
<br>
To view the videos in a bigger picture,<br>
first click "View"--"Full image" in browser (or press "F11").<br>
<br>
Next, please right-click on the video and choose "enlarge" to enlarge.<br>
<br>
Click and hold the mousebutton to scroll over the screen.<br>
If you move the mouse to the upper side you can restore the image size of your browser (or press "F11").<br>
<br>
<br>
WebGR internal version of Flash frontends for *annotations*: <?php echo Zend_Registry::get('VERSION');?><br>